# application.yml - Compatible with Spring Boot 3.5.3 + Java 21
spring:
  application:
    name: emis-app

  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/emis_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: EmisHikariPool

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # Recommended for Spring Boot 3.5+

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# SpringDoc OpenAPI Configuration (Updated for 2.7.0)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  info:
    env:
      enabled: true

# Logging Configuration
logging:
  level:
    com.emis_app: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springdoc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  # Optional: Use H2 for development to avoid PostgreSQL issues
  # Uncomment these lines if you want to test with H2 first:
  # datasource:
  #   url: jdbc:h2:mem:emis_dev_db
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

logging:
  level:
    com.emis_app: DEBUG
    org.springdoc: DEBUG

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:emis_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.emis_app: WARN
    org.hibernate.SQL: WARN